apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: choffmeister/kubernetes-demo-app:1.0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_liveness
              port: http
          readinessProbe:
            httpGet:
              path: /_readiness
              port: http
      terminationGracePeriodSeconds: 60
