apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - name: app
      image: choffmeister/kubernetes-demo-app:1.0
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      env:
        - name: FOO
          value: bar
