build:
	docker build -t choffmeister/kubernetes-demo-app:1.0 -f Dockerfile-1.0 .
	docker push choffmeister/kubernetes-demo-app:1.0
	docker build -t choffmeister/kubernetes-demo-app:2.0 -f Dockerfile-2.0 .
	docker push choffmeister/kubernetes-demo-app:2.0
